In [1]:
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.models import Sequential, Model, load_model
import tensorflow as tf
import pandas as pd
import numpy as np
import joblib

In [2]:
df = pd.read_csv('inference.csv')
df

,user_id,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,...,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback
0,89fd82673d89828f,12,F,Town,Gold Membership,2017-02-15,Yes,Gift Vouchers/Coupons,Smartphone,Mobile_Data,...,17,414.06000,44266.62,23.0,0.00,Yes,No,Yes,No Information Available,Too many ads
1,950537eafbb44d3c,28,M,NaN,Gold Membership,2016-05-13,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,...,17,553.53000,16804.08,17.0,788.61,Yes,No,No,Not Applicable,Quality Customer Care
2,9faebde6d4b687a1,10,F,Town,No Membership,2017-03-23,NaN,Without Offers,Both,Mobile_Data,...,20,1396.78595,41553.32,7.0,630.10,No,Yes,No,Not Applicable,Poor Website
3,b78ce5a21048f32f,23,M,Town,No Membership,2017-05-03,Yes,Without Offers,Smartphone,Wi-Fi,...,16,33.92000,21035.14,17.0,672.39,Yes,No,Yes,Unsolved,Poor Website
4,93e28f5497893452,27,F,Village,Gold Membership,2015-12-10,No,Without Offers,Smartphone,Mobile_Data,...,14,108.29000,28311.16,15.0,784.36,Yes,No,No,Not Applicable,Poor Product Quality
5,8bcd5a0e12317ebc,15,F,Town,No Membership,2015-09-05,Yes,Gift Vouchers/Coupons,Smartphone,Fiber_Optic,...,16,57.22000,36164.10,17.0,594.23,No,Yes,Yes,Solved,Poor Website
6,9c39379fca037a3c,34,M,City,Gold Membership,2017-11-10,Yes,Without Offers,Desktop,Mobile_Data,...,13,84.81000,39121.18,14.0,783.70,No,Yes,Yes,Solved,No reason specified
7,a4a060379f9a8b3e,29,F,City,Premium Membership,2016-05-23,Yes,Credit/Debit Card Offers,Both,Mobile_Data,...,15,556.53000,48371.79,27.0,723.30,Yes,No,Yes,Solved,No reason specified
8,a1f99fee0962df97,36,F,NaN,Basic Membership,2016-07-27,Yes,Gift Vouchers/Coupons,NaN,Wi-Fi,...,19,30.74000,28209.33,19.0,617.41,Yes,No,Yes,Solved,Poor Website
9,8d49be85389c06b8,26,F,Village,Silver Membership,2016-10-01,Yes,Without Offers,Smartphone,Mobile_Data,...,10,0.00000,17920.31,7.0,751.19,No,Yes,Yes,Solved in Follow-up,Poor Product Quality

In [3]:
with open('preprocess.pkl', 'rb') as f:
    pipe_branch = joblib.load(f)

In [4]:
data_inf_final = pd.DataFrame(pipe_branch.transform(df))
data_inf_final

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.624044,-3.609927,0.914087,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,-0.399542,0.543381,0.269467,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.522914,-0.329808,-0.804898,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,-0.241841,-0.096843,0.269467,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.029351,0.519969,0.054594,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.322046,-0.527406,0.269467,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,0.432263,0.516333,-0.052842,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.777053,0.183606,1.343833,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.025556,-0.399714,0.484341,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,-0.357938,0.337245,-0.804898,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
data_inf_final.iloc[:2].values.tolist()

[[0.6240442971285958,
  -3.609926733873189,
  0.9140868643247332,
  4.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0],
 [-0.3995418515206824,
  0.5433812592959841,
  0.26946748112959307,
  4.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0]]

In [6]:
# load model
load_model_func = load_model('ann_wq5.h5')

In [7]:
res_inf = load_model_func.predict(data_inf_final)
res_inf

1/1 [==============================] - 0s 83ms/step

array([[4.2168757e-01],
       [2.2746181e-29],
       [9.6452928e-01],
       [9.6796829e-01],
       [1.9621727e-04],
       [9.5576984e-01],
       [1.8451519e-04],
       [1.0427498e-06],
       [9.8479664e-01],
       [1.1799380e-03]], dtype=float32)

In [8]:
res_inf = np.where(res_inf >= 0.3, 1, 0)
res_inf

array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0]])

In [9]:
df['predict']=res_inf

In [10]:
df

,user_id,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,predict
0,89fd82673d89828f,12,F,Town,Gold Membership,2017-02-15,Yes,Gift Vouchers/Coupons,Smartphone,Mobile_Data,...,414.06000,44266.62,23.0,0.00,Yes,No,Yes,No Information Available,Too many ads,1
1,950537eafbb44d3c,28,M,NaN,Gold Membership,2016-05-13,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,...,553.53000,16804.08,17.0,788.61,Yes,No,No,Not Applicable,Quality Customer Care,0
2,9faebde6d4b687a1,10,F,Town,No Membership,2017-03-23,NaN,Without Offers,Both,Mobile_Data,...,1396.78595,41553.32,7.0,630.10,No,Yes,No,Not Applicable,Poor Website,1
3,b78ce5a21048f32f,23,M,Town,No Membership,2017-05-03,Yes,Without Offers,Smartphone,Wi-Fi,...,33.92000,21035.14,17.0,672.39,Yes,No,Yes,Unsolved,Poor Website,1
4,93e28f5497893452,27,F,Village,Gold Membership,2015-12-10,No,Without Offers,Smartphone,Mobile_Data,...,108.29000,28311.16,15.0,784.36,Yes,No,No,Not Applicable,Poor Product Quality,0
5,8bcd5a0e12317ebc,15,F,Town,No Membership,2015-09-05,Yes,Gift Vouchers/Coupons,Smartphone,Fiber_Optic,...,57.22000,36164.10,17.0,594.23,No,Yes,Yes,Solved,Poor Website,1
6,9c39379fca037a3c,34,M,City,Gold Membership,2017-11-10,Yes,Without Offers,Desktop,Mobile_Data,...,84.81000,39121.18,14.0,783.70,No,Yes,Yes,Solved,No reason specified,0
7,a4a060379f9a8b3e,29,F,City,Premium Membership,2016-05-23,Yes,Credit/Debit Card Offers,Both,Mobile_Data,...,556.53000,48371.79,27.0,723.30,Yes,No,Yes,Solved,No reason specified,0
8,a1f99fee0962df97,36,F,NaN,Basic Membership,2016-07-27,Yes,Gift Vouchers/Coupons,NaN,Wi-Fi,...,30.74000,28209.33,19.0,617.41,Yes,No,Yes,Solved,Poor Website,1
9,8d49be85389c06b8,26,F,Village,Silver Membership,2016-10-01,Yes,Without Offers,Smartphone,Mobile_Data,...,0.00000,17920.31,7.0,751.19,No,Yes,Yes,Solved in Follow-up,Poor Product Quality,0